import data_loader
from data_profiler import profile_all_tables
from data_cleaner import clean_all_tables
from utility.pretty_print_df import print_pretty_data
from utility.pretty_print_profiles import print_pretty_profile
from process import process_and_validate_referrals
from pathlib import Path

report_dir = Path("reports")
report_dir.mkdir(exist_ok=True, parents=True) # create directory for reports
data_source = "./DE_Dataset_intern"

loaded_data = data_loader.data_loader(data_source)
cleaned_data = clean_all_tables(loaded_data)
profiled_data = profile_all_tables(cleaned_data)

def print_to_console():
    """
    Prints cleaned data tables and their profiles to the console.

    This function prints the cleaned data tables with their shapes and the first 30 rows of each table.
    It also prints the profile of each table, which includes statistics such as null counts, distinct counts, and top values.

    Parameters:
        None

    Returns:
        None
    """
    print("\n ================== Showing Tables of Cleaned Data =====================")
    print_pretty_data(cleaned_data)
    print("")
    print("")

    print("\n ================== Showing Profiles of Cleaned Data =====================")
    print_pretty_profile(profiled_data)


def generate_report():
    """
    Generates a report based on the cleaned data.

    The report is generated by calling `process_and_validate_referrals` with the cleaned data.
    If the report directory does not exist, an error message is printed and `None` is returned.
    Otherwise, the report is written to a CSV file in the report directory.

    Returns:
        None
    """
    report = process_and_validate_referrals(cleaned_data)
    if not report_dir.exists():
        print("Error: Report directory does not exist.")
        return None
    report.to_csv(f"{report_dir}/report.csv", sep=",", encoding="utf-8", header=True, index=False)


if __name__ == "__main__":
    print_to_console()
    generate_report()